config/routes.rb
Rails.application.routes.draw do
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  get 'dashboard/products'

  resources :products

  devise_for :users
  
  root 'pages#home'

  post 'products/:id/order', to: 'products#place_order', as: 'place_order'

  post 'checkout/create', to: 'checkout#create'

  get 'pages/checkout', to: 'pages#checkout'

  get 'pages/success', to: 'pages#success', as: 'order_success'
  



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :seller, foreign_key: "buyer_id", class_name: "User"
  belongs_to :buyer, foreign_key: "buyer_id", class_name: "User"
end

app/models/product.rb
class Product < ApplicationRecord
  # mount_uploader :picture, PictureUpLoader
  belongs_to :user
  belongs_to :category
  has_rich_text :description
  has_one_attached :picture

  scope :listing, -> { order created_at: :desc }

  enum condition: {
    new_item: 1,
    used_item: 2
  }
end

app/models/user.rb
class User < ApplicationRecord
  # include Pay::Billable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products

  has_many :sold_orders, foreign_key: "seller_id", class_name: "Order"
  has_many :brought_orders, foreign_key: "buyer_id", class_name: "Order"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

    def create  
      product = Product.find(params[:id])
      @session = Stripe::Checkout::Session.create({
  payment_method_types: ['card', 'link'],
  line_items: [{
    amount: @product.price,
    currency: "aud",
    quantity: 0,
    name: @product.id
  }],
  mode: 'payment',
  success_url: root_url,
  cancel_url: root_url,
})
    respond_to do |format|
        format.json
    end
   end
  end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def products
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.listing
  end

  def success
  end

  def checkout 
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy place_order ]
  before_action :set_form_vars, only: %i[ new edit ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  def search
    @products = Product.where("titl LIKE ?", "%" + params[:q] + "%")
    products_path
  end

  

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end


  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

   def place_order
      Order.create(
        product_id: @product_id,
        seller_id: @product.user.username,
        buyer_id: current_user.username
      )

      @product.update(sold: "sold")
      redirect_to order_success_path
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_form_vars
      @categories = Category.all
      @conditions = Product.conditions.keys
    end

    def authorize_user
      if @product.user_id != current_user.id
        flash[:alert] = "Please sign in"
        redirect_to products_path
      end
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :condition, :sold, :user_id, :category_id, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def format_condition(condition)
        words = condition.split("_").map do |word|
            word.capitalize
        end
        words.join(" ")
    end

    def product_thumbnail product
        # img = product.picture.present? product.picture.thumb.url : "placeholder."
        # image_tag img, class: "product-thumb"
    end

end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/checkout/create.js.erb
var stripe = Stripe("<%= Rails.application.credentails[:stripe][:public_key] %>");

var checkoutButton = document.getElementById( 'checkout-button');

   stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
}).then(function (result) {
    console.log(result.error_message)
});

app/views/dashboard/index.html.erb
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to root_path, class: "nav-link" do  %>
            <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>            
            Home
             <% end %>
          <li class="nav-item">
             <%= link_to products_path, class: "nav-link" do  %>
             <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><polyline points="20 12 20 22 4 22 4 12"></polyline><rect x="2" y="7" width="20" height="5"></rect><line x1="12" y1="22" x2="12" y2="7"></line><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"></path><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"></path></svg> 
             Products
             <% end %>
             <li class="nav-item">
          </li>
        </ul>
      </div>
    </nav>
    <br>

    
  <section class="jumbotron text-center">
    <div class="container">
      <h1>Welcome to Clothes Marketplace</h1>
      <p class="lead text-muted">We have what you need. Whether you're on the hunt for a shirt, dress or a suite, we have it all. Don’t missed out.</p>
    </div>
  </section>


  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
         <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <a href="https://ibb.co/MpqWfSx"><img src="https://i.ibb.co/K7CRDhp/used-dress.png" alt="used-dress" border="0" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"></text></svg></a>
            <div class="card-body">
              <p class="card-text">We have a wide range of women clothes to suit your need. From second hand to new clothes with affordable prices.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <a href="https://ibb.co/QNL8fyb"><img src="https://i.ibb.co/Hz6NV5F/men-shirt.png" alt="men-shirt" border="0" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"></text></svg></a>
            <div class="card-body">
              <p class="card-text">Need a shirt for work? Or for an everyday outing? We have it all! With prices you can afford.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>
         <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <a href="https://imgbb.com/"><img src="https://i.ibb.co/wL4LXrf/men-jean.png" alt="men-jean" border="0" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"></text></svg></a>
            <div class="card-body">
              <p class="card-text">Can’t decide? We have plenty of clothes for your everyday needs. Buy or sell.</p> <span>The rest is up to you</span>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                </div>
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>




  <!-- FOOTER -->
  <footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p><a href="#">Privacy</a> · <a href="#">Terms</a></p>
  </footer>

app/views/dashboard/products.html.erb
<h1>Dashboard#products</h1>
<p>Find me in app/views/dashboard/products.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
  <header>
  <%= render "shared/nav" %>
  </header>

    <p class="notice"><%= notice %></p>  
    <p class="alert"><%= alert %></p>  
 
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    
    <%= yield %>

<%= render "shared/footer"  %>
  </body>
</html>

app/views/pages/checkout.html.erb
<body class="bg-light">
<div class="container">
  <div class="py-5 text-center">
    <h2>Checkout form</h2>
  </div>

  <div class="row">
    <div class="col-md-4 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
    </div>
    <div class="col-md-8 order-md-1">
      <h4 class="mb-3">Billing address</h4>
      <form class="needs-validation" novalidate="">
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="firstName">First name</label>
            <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="lastName">Last name</label>
            <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="username">Username</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">@</span>
            </div>
            <input type="text" class="form-control" id="username" placeholder="Username" required="">
            <div class="invalid-feedback" style="width: 100%;">
              Your username is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="email">Email <span class="text-muted">(Optional)</span></label>
          <input type="email" class="form-control" id="email" placeholder="you@example.com">
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="mb-3">
          <label for="address">Address</label>
          <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="mb-3">
          <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
          <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
        </div>

        <div class="row">
          <div class="col-md-5 mb-3">
            <label for="country">Country</label>
            <select class="custom-select d-block w-100" id="country" required="">
              <option value="">Choose...</option>
              <option>Australia</option>
            </select>
            <div class="invalid-feedback">
              Please select a valid country.
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label for="state">State</label>
            <select class="custom-select d-block w-100" id="state" required="">
              <option value="">Choose...</option>
              <option>Victoria</option>
              <option>Queensland</option>
              <option>NSW</option>
              <option>Tasmania</option>
              <option>Western Australia</option>
              <option>South Australia</option>
              <option>NT</option>
            </select>
            <div class="invalid-feedback">
              Please provide a valid state.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="zip">Zip</label>
            <input type="text" class="form-control" id="zip" placeholder="" required="">
            <div class="invalid-feedback">
              Zip code required.
            </div>
          </div>
        </div>
        <hr class="mb-4">
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="same-address">
          <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
        </div>
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="save-info">
          <label class="custom-control-label" for="save-info">Save this information for next time</label>
        </div>
        <hr class="mb-4">

        <h4 class="mb-3">Payment</h4>

        <div class="d-block my-3">
          <div class="custom-control custom-radio">
            <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked="" required="">
            <label class="custom-control-label" for="credit">Credit card</label>
          </div>
          <div class="custom-control custom-radio">
            <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required="">
            <label class="custom-control-label" for="debit">Debit card</label>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="cc-name">Name on card</label>
            <input type="text" class="form-control" id="cc-name" placeholder="" required="">
            <small class="text-muted">Full name as displayed on card</small>
            <div class="invalid-feedback">
              Name on card is required
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="cc-number">Credit card number</label>
            <input type="text" class="form-control" id="cc-number" placeholder="" required="">
            <div class="invalid-feedback">
              Credit card number is required
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 mb-3">
            <label for="cc-expiration">Expiration</label>
            <input type="text" class="form-control" id="cc-expiration" placeholder="" required="">
            <div class="invalid-feedback">
              Expiration date required
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="cc-cvv">CVV</label>
            <input type="text" class="form-control" id="cc-cvv" placeholder="" required="">
            <div class="invalid-feedback">
              Security code required
            </div>
          </div>
        </div>
        <hr class="mb-4">
        <%= button_to "Pay now", checkout_order_path class: "nav-link"%> 
      </form>
    </div>
  </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.6/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
        <script src="form-validation.js"></script>
</body>

app/views/pages/home.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Marketplace for New and Used Clothes</h1>
      <p>Easy to buy and sell!</p>
    </div>
  </div>

  <section id="listing-procducts">
   <div class="container">
    <div class="row">
  <%= render "products/listing" %>
  </div>
  </div>
  </section>

  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h2>Men</h2>
        <p>Thousands of new and used clothes. Affordable and unqiue clothes in just one website.</p>
        <%# <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p> %>
      </div>
      <div class="col-md-4">
        <h2>Women</h2>
        <p>Thousands of new and used clothes. Affordable and unqiue clothes in just one website.</p>
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

</main>

app/views/pages/success.html.erb
<h2>Thanks for your order</h2>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="form-group">
    <% @conditions.each do |option| %>
    <%= form.label :condition, format_condition(option) %>
    <%= form.radio_button :condition, option %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]} %>
  </div>

 <div class="form-group">
    <%= form.label :picture %>
    <%= form.file_field :picture, class: "form-control"%>
    <%= form.hidden_field :picture_cache %>
  </div>

  <%# <div class="form-group"> %>
    <%# <%= form.label :picture %> 
    <%# <%= form.file_field :picture, accept: "image/png,image/jpeg,image/jpg"%> 
  <%# </div> %>

  <div class="form-group">
    <%= form.submit "Create Product", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/products/index.html.erb
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-6">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-6 mb-3 border-bottom">
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-6">
          </div>
          </div>
          </div>
<p id="notice"><%= notice %></p>

<h1 class="h3">Products</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Condition</th>
      <th>Sold</th>
      <th>User</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.condition %></td>
        <td><%= product.sold %></td>
        <td><%= product.user_id %></td>
        <td><%= product.category_id %></td>
        <%# <td><%= button_to 'Buy now!', checkout_create_path %></td>
        <%# <td><%= button_to "Submit Payment", checkout_create_path, params: {:product_id => product.id }, remote: true %></td>
        <td><%= link_to 'Show', product, class: "btn btn-info" %></td>
        <% if current_user && current_user.id == product.user_id %>
        <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Product', new_product_path, class: "btn btn-secondary"  %>

app/views/products/search.html.erb
<h1>Search Results</h1>
<%= render @products %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">  <%= @product.title %></h1>
  <p class="lead"></p>
  <hr class="my-4">
<div>

<% if @product.picture.attached? %>
  <%= image_tag @product.picture, alt: @product.title %>
  <% else %>
  <%= image_tag "https://ibb.co/G7Qpsyv", alt: @product.title %>
  <% end %>
</div>
<br>
<% if @product.sold %>
<h2>SOLD</h2>
<% elsif current_user && !@product.sold %>
<%= button_to "Buy now", place_order_path, class: "nav-link"%>  
<% else %>
<p> Please log in to purchase</p>
<% end %>
<br>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @product.condition %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @product.sold %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>
  
<% if current_user && current_user.id == @product.user_id %>
<%= link_to 'Edit', edit_product_path(@product), class:"btn btn-secondary" %> |
<% end %>
<%= link_to 'Back', products_path, class:"btn btn-dark"  %>
</div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <% if user_signed_in? %>
       <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
       <% else %>
      <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>  
      <% end %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>        
      </li>
       <%# <li class="nav-item"> %>
      <%# <%= link_to "Products", products_path, class: "nav-link"  %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div></nav> 
<%= link_to "Home", root_path %>

app/views/shared/_sidebar.html.erb
<nav class="col-md-2 d-none d-dm-block bg-light sidebar">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to dashboard_path, class: "nav-link" do %>
            <% end %>
            <%= link_to products_path, class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
              Products <span class="sr-only">(current)</span>
            <% end %>
          </li>
          
          </li>
        </ul>
      </div>
    </nav>